apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ez7wxhbok-nodejs
  janus-idp.io/tekton: ez7wxhbok-nodejs
  backstage.io/kubernetes-id: ez7wxhbok-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ez7wxhbok-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
