apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ez7wxhbok-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ez7wxhbok-nodejs 
  name: ez7wxhbok-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ez7wxhbok-nodejs 
